# this won't be necessary once all dependencies have updated for 9.2
# and it wouldn't be necessary if we could use `source-repository-package`, `allow-newer` etc. in cabal scripts...
cabal run Build.hs --project-file haskell/cabal.project --builddir .build/hs --write-ghc-environment-files=always
