{-# LANGUAGE CPP #-}

--TODO this is a workaround until we have something like https://github.com/dhall-lang/dhall-haskell/issues/1521
module DhallHack (defaultSimple) where

import Data.Bifunctor
import Dhall
import Embed
import Layout

defaultSimple :: IO (Layout () ())
defaultSimple = bimap mempty mempty <$> layout

layout :: IO (Layout A B)
layout = input auto $ defaultDhall ()

#if linux_HOST_OS
data A
    = AbsBrake
    | AbsDistance
    | AbsGas
    | AbsHat0x
    | AbsHat0y
    | AbsHat1x
    | AbsHat1y
    | AbsHat2x
    | AbsHat2y
    | AbsHat3x
    | AbsHat3y
    | AbsMisc
    | AbsMtBlobId
    | AbsMtDistance
    | AbsMtOrientation
    | AbsMtPositionX
    | AbsMtPositionY
    | AbsMtPressure
    | AbsMtSlot
    | AbsMtToolType
    | AbsMtToolX
    | AbsMtToolY
    | AbsMtTouchMajor
    | AbsMtTouchMinor
    | AbsMtTrackingId
    | AbsMtWidthMajor
    | AbsMtWidthMinor
    | AbsPressure
    | AbsReserved
    | AbsRudder
    | AbsRx
    | AbsRy
    | AbsRz
    | AbsThrottle
    | AbsTiltX
    | AbsTiltY
    | AbsToolWidth
    | AbsVolume
    | AbsWheel
    | AbsX
    | AbsY
    | AbsZ
    deriving (Generic, FromDhall)
data B
    = Btn0
    | Btn1
    | Btn2
    | Btn3
    | Btn4
    | Btn5
    | Btn6
    | Btn7
    | Btn8
    | Btn9
    | BtnA
    | BtnB
    | BtnBack
    | BtnBase
    | BtnBase2
    | BtnBase3
    | BtnBase4
    | BtnBase5
    | BtnBase6
    | BtnC
    | BtnDead
    | BtnDigi
    | BtnDpadDown
    | BtnDpadLeft
    | BtnDpadRight
    | BtnDpadUp
    | BtnEast
    | BtnExtra
    | BtnForward
    | BtnGamepad
    | BtnGearDown
    | BtnGearUp
    | BtnJoystick
    | BtnLeft
    | BtnMiddle
    | BtnMisc
    | BtnMode
    | BtnMouse
    | BtnNorth
    | BtnPinkie
    | BtnRight
    | BtnSelect
    | BtnSide
    | BtnSouth
    | BtnStart
    | BtnStylus
    | BtnStylus2
    | BtnTask
    | BtnThumb
    | BtnThumb2
    | BtnThumbl
    | BtnThumbr
    | BtnTl
    | BtnTl2
    | BtnToolAirbrush
    | BtnToolBrush
    | BtnToolDoubletap
    | BtnToolFinger
    | BtnToolLens
    | BtnToolMouse
    | BtnToolPen
    | BtnToolPencil
    | BtnToolQuadtap
    | BtnToolQuinttap
    | BtnToolRubber
    | BtnToolTripletap
    | BtnTop
    | BtnTop2
    | BtnTouch
    | BtnTr
    | BtnTr2
    | BtnTrigger
    | BtnTriggerHappy
    | BtnTriggerHappy1
    | BtnTriggerHappy10
    | BtnTriggerHappy11
    | BtnTriggerHappy12
    | BtnTriggerHappy13
    | BtnTriggerHappy14
    | BtnTriggerHappy15
    | BtnTriggerHappy16
    | BtnTriggerHappy17
    | BtnTriggerHappy18
    | BtnTriggerHappy19
    | BtnTriggerHappy2
    | BtnTriggerHappy20
    | BtnTriggerHappy21
    | BtnTriggerHappy22
    | BtnTriggerHappy23
    | BtnTriggerHappy24
    | BtnTriggerHappy25
    | BtnTriggerHappy26
    | BtnTriggerHappy27
    | BtnTriggerHappy28
    | BtnTriggerHappy29
    | BtnTriggerHappy3
    | BtnTriggerHappy30
    | BtnTriggerHappy31
    | BtnTriggerHappy32
    | BtnTriggerHappy33
    | BtnTriggerHappy34
    | BtnTriggerHappy35
    | BtnTriggerHappy36
    | BtnTriggerHappy37
    | BtnTriggerHappy38
    | BtnTriggerHappy39
    | BtnTriggerHappy4
    | BtnTriggerHappy40
    | BtnTriggerHappy5
    | BtnTriggerHappy6
    | BtnTriggerHappy7
    | BtnTriggerHappy8
    | BtnTriggerHappy9
    | BtnWest
    | BtnWheel
    | BtnX
    | BtnY
    | BtnZ
    | Key0
    | Key1
    | Key102nd
    | Key10channelsdown
    | Key10channelsup
    | Key2
    | Key3
    | Key4
    | Key5
    | Key6
    | Key7
    | Key8
    | Key9
    | KeyA
    | KeyAb
    | KeyAddressbook
    | KeyAgain
    | KeyAlsToggle
    | KeyAlterase
    | KeyAngle
    | KeyApostrophe
    | KeyAppselect
    | KeyArchive
    | KeyAttendantOff
    | KeyAttendantOn
    | KeyAttendantToggle
    | KeyAudio
    | KeyAux
    | KeyB
    | KeyBack
    | KeyBackslash
    | KeyBackspace
    | KeyBassboost
    | KeyBattery
    | KeyBlue
    | KeyBluetooth
    | KeyBookmarks
    | KeyBreak
    | KeyBrightnessAuto
    | KeyBrightnessCycle
    | KeyBrightnessMax
    | KeyBrightnessMin
    | KeyBrightnessToggle
    | KeyBrightnessZero
    | KeyBrightnessdown
    | KeyBrightnessup
    | KeyBrlDot1
    | KeyBrlDot10
    | KeyBrlDot2
    | KeyBrlDot3
    | KeyBrlDot4
    | KeyBrlDot5
    | KeyBrlDot6
    | KeyBrlDot7
    | KeyBrlDot8
    | KeyBrlDot9
    | KeyButtonconfig
    | KeyC
    | KeyCalc
    | KeyCalendar
    | KeyCamera
    | KeyCameraDown
    | KeyCameraFocus
    | KeyCameraLeft
    | KeyCameraRight
    | KeyCameraUp
    | KeyCameraZoomin
    | KeyCameraZoomout
    | KeyCancel
    | KeyCapslock
    | KeyCd
    | KeyChannel
    | KeyChanneldown
    | KeyChannelup
    | KeyChat
    | KeyClear
    | KeyClose
    | KeyClosecd
    | KeyCoffee
    | KeyComma
    | KeyCompose
    | KeyComputer
    | KeyConfig
    | KeyConnect
    | KeyContextMenu
    | KeyControlpanel
    | KeyCopy
    | KeyCut
    | KeyCyclewindows
    | KeyD
    | KeyDashboard
    | KeyDatabase
    | KeyDelEol
    | KeyDelEos
    | KeyDelLine
    | KeyDelete
    | KeyDeletefile
    | KeyDigits
    | KeyDirection
    | KeyDirectory
    | KeyDisplayOff
    | KeyDisplaytoggle
    | KeyDocuments
    | KeyDollar
    | KeyDot
    | KeyDown
    | KeyDvd
    | KeyE
    | KeyEdit
    | KeyEditor
    | KeyEjectcd
    | KeyEjectclosecd
    | KeyEmail
    | KeyEnd
    | KeyEnter
    | KeyEpg
    | KeyEqual
    | KeyEsc
    | KeyEuro
    | KeyExit
    | KeyF
    | KeyF1
    | KeyF10
    | KeyF11
    | KeyF12
    | KeyF13
    | KeyF14
    | KeyF15
    | KeyF16
    | KeyF17
    | KeyF18
    | KeyF19
    | KeyF2
    | KeyF20
    | KeyF21
    | KeyF22
    | KeyF23
    | KeyF24
    | KeyF3
    | KeyF4
    | KeyF5
    | KeyF6
    | KeyF7
    | KeyF8
    | KeyF9
    | KeyFastforward
    | KeyFavorites
    | KeyFile
    | KeyFinance
    | KeyFind
    | KeyFirst
    | KeyFn
    | KeyFn1
    | KeyFn2
    | KeyFnB
    | KeyFnD
    | KeyFnE
    | KeyFnEsc
    | KeyFnF
    | KeyFnF1
    | KeyFnF10
    | KeyFnF11
    | KeyFnF12
    | KeyFnF2
    | KeyFnF3
    | KeyFnF4
    | KeyFnF5
    | KeyFnF6
    | KeyFnF7
    | KeyFnF8
    | KeyFnF9
    | KeyFnS
    | KeyForward
    | KeyForwardmail
    | KeyFrameback
    | KeyFrameforward
    | KeyFront
    | KeyG
    | KeyGames
    | KeyGoto
    | KeyGraphicseditor
    | KeyGrave
    | KeyGreen
    | KeyH
    | KeyHangeul
    | KeyHanguel
    | KeyHanja
    | KeyHelp
    | KeyHenkan
    | KeyHiragana
    | KeyHome
    | KeyHomepage
    | KeyHp
    | KeyI
    | KeyImages
    | KeyInfo
    | KeyInsLine
    | KeyInsert
    | KeyIso
    | KeyJ
    | KeyJournal
    | KeyK
    | KeyKatakana
    | KeyKatakanahiragana
    | KeyKbdillumdown
    | KeyKbdillumtoggle
    | KeyKbdillumup
    | KeyKbdinputassistAccept
    | KeyKbdinputassistCancel
    | KeyKbdinputassistNext
    | KeyKbdinputassistNextgroup
    | KeyKbdinputassistPrev
    | KeyKbdinputassistPrevgroup
    | KeyKeyboard
    | KeyKp0
    | KeyKp1
    | KeyKp2
    | KeyKp3
    | KeyKp4
    | KeyKp5
    | KeyKp6
    | KeyKp7
    | KeyKp8
    | KeyKp9
    | KeyKpasterisk
    | KeyKpcomma
    | KeyKpdot
    | KeyKpenter
    | KeyKpequal
    | KeyKpjpcomma
    | KeyKpleftparen
    | KeyKpminus
    | KeyKpplus
    | KeyKpplusminus
    | KeyKprightparen
    | KeyKpslash
    | KeyL
    | KeyLanguage
    | KeyLast
    | KeyLeft
    | KeyLeftalt
    | KeyLeftbrace
    | KeyLeftctrl
    | KeyLeftmeta
    | KeyLeftshift
    | KeyLightsToggle
    | KeyLinefeed
    | KeyList
    | KeyLogoff
    | KeyM
    | KeyMacro
    | KeyMail
    | KeyMedia
    | KeyMediaRepeat
    | KeyMemo
    | KeyMenu
    | KeyMessenger
    | KeyMhp
    | KeyMicmute
    | KeyMinus
    | KeyMode
    | KeyMove
    | KeyMp3
    | KeyMsdos
    | KeyMuhenkan
    | KeyMute
    | KeyN
    | KeyNew
    | KeyNews
    | KeyNext
    | KeyNextsong
    | KeyNumeric0
    | KeyNumeric1
    | KeyNumeric2
    | KeyNumeric3
    | KeyNumeric4
    | KeyNumeric5
    | KeyNumeric6
    | KeyNumeric7
    | KeyNumeric8
    | KeyNumeric9
    | KeyNumericA
    | KeyNumericB
    | KeyNumericC
    | KeyNumericD
    | KeyNumericPound
    | KeyNumericStar
    | KeyNumlock
    | KeyO
    | KeyOk
    | KeyOpen
    | KeyOption
    | KeyP
    | KeyPagedown
    | KeyPageup
    | KeyPaste
    | KeyPause
    | KeyPausecd
    | KeyPc
    | KeyPhone
    | KeyPlay
    | KeyPlaycd
    | KeyPlayer
    | KeyPlaypause
    | KeyPower
    | KeyPower2
    | KeyPresentation
    | KeyPrevious
    | KeyPrevioussong
    | KeyPrint
    | KeyProg1
    | KeyProg2
    | KeyProg3
    | KeyProg4
    | KeyProgram
    | KeyProps
    | KeyPvr
    | KeyQ
    | KeyQuestion
    | KeyR
    | KeyRadio
    | KeyRecord
    | KeyRed
    | KeyRedo
    | KeyRefresh
    | KeyReply
    | KeyReserved
    | KeyRestart
    | KeyRewind
    | KeyRfkill
    | KeyRight
    | KeyRightalt
    | KeyRightbrace
    | KeyRightctrl
    | KeyRightmeta
    | KeyRightshift
    | KeyRo
    | KeyRotateDisplay
    | KeyS
    | KeySat
    | KeySat2
    | KeySave
    | KeyScale
    | KeyScreen
    | KeyScreenlock
    | KeyScreensaver
    | KeyScrolldown
    | KeyScrolllock
    | KeyScrollup
    | KeySearch
    | KeySelect
    | KeySemicolon
    | KeySend
    | KeySendfile
    | KeySetup
    | KeyShop
    | KeyShuffle
    | KeySlash
    | KeySleep
    | KeySlow
    | KeySound
    | KeySpace
    | KeySpellcheck
    | KeySport
    | KeySpreadsheet
    | KeyStop
    | KeyStopcd
    | KeySubtitle
    | KeySuspend
    | KeySwitchvideomode
    | KeySysrq
    | KeyT
    | KeyTab
    | KeyTape
    | KeyTaskmanager
    | KeyTeen
    | KeyText
    | KeyTime
    | KeyTitle
    | KeyTouchpadOff
    | KeyTouchpadOn
    | KeyTouchpadToggle
    | KeyTuner
    | KeyTv
    | KeyTv2
    | KeyTwen
    | KeyU
    | KeyUndo
    | KeyUnknown
    | KeyUp
    | KeyUwb
    | KeyV
    | KeyVcr
    | KeyVcr2
    | KeyVendor
    | KeyVideo
    | KeyVideoNext
    | KeyVideoPrev
    | KeyVideophone
    | KeyVoicecommand
    | KeyVoicemail
    | KeyVolumedown
    | KeyVolumeup
    | KeyW
    | KeyWakeup
    | KeyWimax
    | KeyWlan
    | KeyWordprocessor
    | KeyWpsButton
    | KeyWwan
    | KeyWww
    | KeyX
    | KeyXfer
    | KeyY
    | KeyYellow
    | KeyYen
    | KeyZ
    | KeyZenkakuhankaku
    | KeyZoom
    | KeyZoomin
    | KeyZoomout
    | KeyZoomreset
    deriving (Generic, FromDhall)
#else
data A = A
    deriving (Generic, FromDhall)
data B = B
    deriving (Generic, FromDhall)
#endif
